<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http:///org/gnstudio/apdt/model.ecore" nsPrefix="apdt">
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//SequenceProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="0.2.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="release" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encoding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programs" upperBound="-1"
        eType="#//Program" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//PackageElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceElement" eType="#//InterfaceElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classElement" eType="#//ClassElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatedBy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessType">
    <eLiterals name="PUBLIC"/>
    <eLiterals name="INTERNAL"/>
    <eLiterals name="PROTECTED"/>
    <eLiterals name="PRIVATE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeclarationType">
    <eLiterals name="DEFAULT"/>
    <eLiterals name="FINAL"/>
    <eLiterals name="STATIC"/>
    <eLiterals name="OVERRIDDEN"/>
    <eLiterals name="CONSTANT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MethodType">
    <eLiterals name="STANDARD"/>
    <eLiterals name="GETTER"/>
    <eLiterals name="SETTER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IterationType">
    <eLiterals name="FOR" literal="for"/>
    <eLiterals name="FOR_EACH" literal="for-each"/>
    <eLiterals name="WHILE" literal="while"/>
    <eLiterals name="DO_WHILE" literal="do-while"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Discussion" eSuperTypes="#//Description">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptionProvider" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//Description"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscussionProvider" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="discussions" upperBound="-1"
        eType="#//Discussion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceLink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceLinkProvider" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//SourceLink"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program" eSuperTypes="#//DescriptionProvider #//DiscussionProvider #//SourceLinkProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//PackageElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageElement" eSuperTypes="#//DiscussionProvider #//SourceLinkProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//InterfaceElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//ClassElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceElement" eSuperTypes="#//DescriptionProvider #//DiscussionProvider #//SourceLinkProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="#//AccessType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendsElements" upperBound="-1"
        eType="#//TypeReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//Method" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassElement" eSuperTypes="#//DescriptionProvider #//DiscussionProvider #//SourceLinkProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="#//AccessType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynamic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementsElements" upperBound="-1"
        eType="#//TypeReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendsElements" upperBound="-1"
        eType="#//TypeReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//Method" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//ClassMember" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassMember" eSuperTypes="#//DescriptionProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="#//AccessType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declaration" eType="#//DeclarationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//DescriptionProvider #//DiscussionProvider #//SequenceProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" eType="#//MethodSignature"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="throwsElements" upperBound="-1"
        eType="#//TypeReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//MethodArgument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodSignature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="#//AccessType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MethodType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declaration" eType="#//DeclarationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varargs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//TypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodArgument" eSuperTypes="#//DescriptionProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceProvider" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" upperBound="-1"
        eType="#//Sequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//DescriptionProvider #//Sequence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declaration" eType="#//DeclarationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//Description #//Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceGroup" eSuperTypes="#//DescriptionProvider #//Sequence #//SequenceProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Iteration" eSuperTypes="#//SequenceGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//IterationType"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodCall" eSuperTypes="#//DescriptionProvider #//Sequence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arguments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodReturn" eSuperTypes="#//Sequence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchSequence" eSuperTypes="#//Sequence #//DescriptionProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//SequenceGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultCase" eType="#//SequenceGroup"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlSequence" eSuperTypes="#//Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifGroup" eType="#//SequenceGroup"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseifGroups" upperBound="-1"
        eType="#//SequenceGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseGroup" eType="#//SequenceGroup"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrySequence" eSuperTypes="#//Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tryGroup" eType="#//SequenceGroup"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catchGroups" upperBound="-1"
        eType="#//SequenceGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finallyGroup" eType="#//SequenceGroup"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Recursion" eSuperTypes="#//Description #//Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Print" eSuperTypes="#//Description #//Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Read" eSuperTypes="#//Description #//Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Write" eSuperTypes="#//Description #//Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Recover" eSuperTypes="#//Description #//Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Store" eSuperTypes="#//Description #//Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalculateStore" eSuperTypes="#//Description #//Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Show" eSuperTypes="#//Description #//Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Prompt" eSuperTypes="#//Description #//Sequence"/>
</ecore:EPackage>
